// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_SimpleChecksum","status":true,"description":"A plugin to get and compare hashes.\r\nBeware! This is a simple, non-secure hash!","parameters":{}}
];
